### ISSUE TITLE
missing import of  Time module

### ISSUE THREAD

**Issue by junakowicz** [evancz/task-tutorial#2]
While trying to follow [task tutorial](http://elm-lang.org/learn/Tasks.elm) I got this

```
Error in package evancz/task-tutorial 1.0.0 in module TaskTutorial:

Error in definition getCurrentTime:
Could not find type 'Time'
```

Sorry I can see that this was fixed on master but while running 
`elm-package install evancz/task-tutorial`

I get version from tag 1.0.0

**Comment by evancz** [comment]
Oops, sorry about that! I just published 1.0.1. Please let me know if there are still issues!
