### ISSUE TITLE
Bump package to 1.0.2

### ISSUE THREAD

**Issue by novaluke** [evancz/task-tutorial#4]
The [Tasks tutorial](http://elm-lang.org/guide/reactivity#tasks) blows up on the second example without the changes from 1f21350d28ff5562caf141bec2ec2ea7fa0f3712. Spending an hour trying to figure out what I'd done wrong (only to find out it wasn't my mistake for once!) makes the tutorial a bit of an underwhelming experience. Please bump the package version to include the changes so that we (both myself and others) don't keep downloading a broken version.

**Comment by evancz** [comment]
Thanks for opening an issue for this, should be released now!

**Comment by novaluke** [comment]
Thanks!
