### ISSUE TITLE
Uncaught Error: 'main' is missing! What do I display?!

### ISSUE THREAD

**Issue by martinos** [evancz/task-tutorial#5]
When I run the `TaskTutorial.elm`, I get the following error in the console:

```
Uncaught Error: 'main' is missing! What do I display?!
```

Note: I am on elm 0.15.1

**Comment by martinos** [comment]
Sorry, I misread the tutorial. You can close this issue.

**Comment by evancz** [comment]
Okay, no worries! If you want to share, let me know what went wrong. Maybe I can improve the tutorial!

**Comment by amitaibu** [comment]
> Maybe I can improve the tutorial!

On the first example we don't have `main = ...` so we see this error. Maybe it could be `main = show "open your console"`

**Comment by manumax** [comment]
Definitely! I lost about 20 minutes to understand I had to look at the console log and when I finally did it, at first, I didn't realise those number where actually the printed timestamps (yeah, it is Friday for everyone :))
