### ISSUE TITLE
Can't load READMe file

### ISSUE THREAD

**Issue by amitaibu** [evancz/task-tutorial#6]
From console.log: `XMLHttpRequest cannot load http://package.elm-lang.org/packages/elm-lang/core/latest/README.md. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

Also, I think it would make sense in the tutorial repo to already include all the needed libraries, so one wouldn't have to install those packages / Or maybe indicate as the tutorials advances those libraries need to be downloaded?

**Comment by amitaibu** [comment]
btw, with https://raw.githubusercontent.com/evancz/elm-architecture-tutorial/master/README.md the example works :)

**Comment by evancz** [comment]
Can you do a PR that switches to that link?

**Comment by amitaibu** [comment]
Closing in favor of https://github.com/elm-lang/elm-lang.org/pull/359
